### ISSUE TITLE
Iteraciones

### ISSUE THREAD

**Issue by SashaFran** [Claudi-Dominguez/TPE-TIO#3]
**Modificacion del archivo ".md" sobre Python. En este caso hago una actualizacion sobre "Iteraciones" al final del mismo dejo la biografia utilizada.**
>Recomiendo el uso de "Notepad++" para su modificacion y no "Bloc de Notas" o "Notepad" comun.

## Iteraciones:
Se denomina iteración a aquel conjunto de instrucciones que se encuentran acotadas por un bloque repetitivo de acciones indicadas a través de comandos indicadas en el lenguaje Python. Las instrucciones por excelencia en este lenguaje pertenecen a los bloques *for* y *while*. Estos bloques poseen indentación para reconocer el bloque como tal.

Cuando iteramos sobre diccionarios, se pueden obtener al mismo tiempo la clave y su valor correspondiente usando el método *iteritems()*
.
Cuando se itera sobre una secuencia, se puede obtener el índice de posición junto a su valor correspondiente usando la función *enumerate()*
.
Para iterar sobre dos o más secuencias al mismo tiempo, los valores pueden emparejarse con la función *zip()*

Para iterar sobre una secuencia en orden inverso, se especifica primero la secuencia al derecho y luego se llama a la función *reversed()*

Para iterar sobre una secuencia ordenada, se utiliza la función *sorted()* la cual devuelve una nueva lista ordenada dejando a la original intacta.

http://docs.python.org.ar/tutorial/2/datastructures.html

**Comment by claracamejo** [comment]
Se agrego información y se actualizo algunos puntos
